name: Build

on:
  push:
    branches: [main]
  pull_request:    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: yarn
    - run: yarn install
    - run: yarn run:webpack
    - run: yarn run:esbuild
    - run: yarn run:vite
